#!/bin/bash
# This script is for the Jupyter notebook demo binder
set -e
pwd
pip install -r requirements-dev.txt
pip install -r requirements.txt
pushd bindings/python/pydeck/
jupyter nbextension install --sys-prefix --symlink --overwrite --py pydeck
jupyter nbextension enable --sys-prefix --py pydeck
echo "Successfully installed pydeck"
